version: "3"

services:
  db:
    container_name: myDB
    image: postgres:11
    environment:
      - POSTGRES_DB= postgres
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres

  web:
    container_name: django_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_app
    ports:
    - "8000:8000"
    depends_on:
      - db
